Develop
mate-academy/react_todo-app pull request #1039
Opened 2024-08-13 20:53 UTC by BoGoBooM

[DEMO LINK](https://bogoboom.github.io/react_todo-app/)

2024-08-14 15:43 UTC, etojeDenys requested changes
your demo link doesn't work, try to fix that and then re-request the review

2024-08-15 15:00 UTC, SanyaBratashchuk approved these changes
handle plural it should be `1 item` but `2 items`
![image](https://github.com/user-attachments/assets/1002ee4a-39c0-4859-a9ce-83eca78cd13b)

2024-08-15 15:00 UTC, SanyaBratashchuk commented on src/App.tsx
> +  const inputElement = useRef<HTMLInputElement>(null);
```suggestion
  const inputElementRef = useRef<HTMLInputElement>(null);
```

2024-08-15 15:00 UTC, SanyaBratashchuk commented on src/App.tsx
> +  });
move filter inside switch case not vice versa. To avoid redundant iteration in default case

2025-02-17 11:45 UTC, closed without merging