.idea was added to gitignore
mate-academy/react_todo-app pull request #175
Opened 2020-05-08 13:32 UTC by FaychakA

[DEMO LINK](https://FaychakA.github.io/react_todo-app/)

2020-05-08 15:50 UTC, irenhh requested changes
![image](https://user-images.githubusercontent.com/33497431/81422352-85bc8f00-915b-11ea-9d66-79c5184b0365.png)
don't allow empty todo

![image](https://user-images.githubusercontent.com/33497431/81422403-93721480-915b-11ea-9b51-e68df6a07a35.png)
all todos checked -> 'check all' button should be active

mark the tab that is selected

what's the matter with names?

2020-05-08 15:50 UTC, irenhh commented on src/App.js
> +    toggleAll: false,
`toggleAll` is a name for a function, use `isToggledAll` (as if you wanna answer yes-no)

2020-05-08 15:50 UTC, irenhh commented on src/App.js
> +          ...el, completed: !el.completed,
```suggestion
          ...el, 
          completed: !el.completed,
```

2020-05-08 15:50 UTC, irenhh commented on src/App.js
> +  check = () => {
check what?

2020-05-08 15:50 UTC, irenhh commented on src/App.js
> +  remove = (id) => {
remove what?

2020-05-08 15:50 UTC, irenhh commented on src/App.js
> +  handleClear = () => {
handleClear what?

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +class TodoList extends React.Component {
replace with function component

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +  handleAllToggle = () => {
do this inline, there is no need to create another method just to pass a prop

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +  filt = (arr) => {
filt??

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +    if (this.props.filter === 'All') {
destructuring

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +    this.props.remove(+event.target.id);
remove what?

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +          checked={this.props.toggleAll}
destructuring

2020-05-08 15:50 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +          {this.filt(this.props.items).length === 0
pass already filtered list to TodoList

2020-05-08 15:50 UTC, irenhh commented on src/components/TodosFilter/TodosFilter.js
> +class TodosFilter extends React.Component {
if you don't use state, move to function component

2020-05-08 15:50 UTC, irenhh commented on src/components/TodosFilter/TodosFilter.js
> +  handleFilter = (filterName) => {
the same problem

2020-05-12 15:28 UTC, denys-cheporniuk requested changes
перевірь завдання по checklist
https://github.com/mate-academy/react_todo-app/blob/master/checklist.md

2020-05-13 13:54 UTC, denys-cheporniuk approved these changes

2026-01-12 09:46 UTC, closed without merging