solution
mate-academy/react_todo-app pull request #343
Opened 2022-01-10 16:19 UTC by Bohdan996

[DEMO LINK](https://Bohdan996.github.io/react_todo-app/)

2022-01-11 14:26 UTC, danylo-onishchuk requested changes
нашел баг

<img width="708" alt="Screenshot 2022-01-11 at 16 25 59" src="https://user-images.githubusercontent.com/78209611/148960988-b4a3e081-1498-4b34-8ca7-3417ef228f0e.png">

<img width="795" alt="Screenshot 2022-01-11 at 16 25 55" src="https://user-images.githubusercontent.com/78209611/148961000-00ff3446-4444-4ceb-b059-e629d6418f5f.png">


при редактировании тудушки в инпут попадает что то из старого стейта

2022-01-12 13:05 UTC, aliceblunt8 requested changes
- I can change todo's text for empty string
![image](https://user-images.githubusercontent.com/57598825/149145634-e3e8a7af-b02a-4495-b0fe-bb41645e6962.png)

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/Footer/Footer.tsx
> +            className={sortQuery === 'active' ? 'selected' : ''}
use classNames lib
https://www.npmjs.com/package/classnames

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/Footer/Footer.tsx
> +      {todos.some(todo => todo.completed === true) && (
```suggestion
      {todos.some(todo => todo.completed) && (
```

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/Footer/Footer.tsx
> +          onClick={() => clearCopleted()}
```suggestion
          onClick={clearCompleted}
```

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/Form/Form.tsx
> +      onSubmit={(e) => handleSubmit(e)}
```suggestion
      onSubmit={handleSubmit}
```

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/Form/Form.tsx
> +        onClick={() => arrowButtonClick()}
```suggestion
        onClick={arrowButtonClick}
```

2022-01-12 13:05 UTC, aliceblunt8 commented on src/components/TodoApp/TodoApp.tsx
> +    const active = todos.filter(a => a.completed !== true);
```suggestion
    const active = todos.filter(todo => !todo.completed);
```

2022-01-12 14:35 UTC, aliceblunt8 approved these changes

2022-11-26 14:10 UTC, closed without merging