finished react_todo_app
mate-academy/react_todo-app pull request #571
Opened 2023-06-15 22:32 UTC by pushkarskiyrodion

[DEMO LINK](https://pushkarskiyrodion.github.io/react_todo-app/)

2023-06-16 14:28 UTC, loralevitska requested changes
Keep up the good work! Some comments to fix:

- don't change footer due to filters. Check yourself according [example](https://todomvc.com/examples/vanillajs/#/completed)
![image](https://github.com/mate-academy/react_todo-app/assets/70009205/1373a9bd-2489-4bc2-b9a3-d5e1ba061bcf)
- add right condition for 1 item left 
![image](https://github.com/mate-academy/react_todo-app/assets/70009205/e8edfb8e-ae0c-471f-a943-587bdfa3c381)

2023-06-16 14:28 UTC, loralevitska commented on src/App.tsx
> +} from './api/todos';
```suggestion
import {
  USER_ID, 
  deleteTodo, 
  getTodos, 
  patchTodos, 
  postTodos,
} from './api/todos';
```

2023-06-16 14:28 UTC, loralevitska commented on src/App.tsx
> +    };
Create function out of `useEffect`

2023-06-16 14:28 UTC, loralevitska commented on src/App.tsx
> +          return todo;
```suggestion
      switch (filterValue) {
        case Filter.Active:
          return !todo.completed;
          
        case Filter.Completed:
          return todo.completed;
          
        default:
          return todo;
```

2023-06-16 14:28 UTC, loralevitska commented on src/components/NewTodo/NewTodo.tsx
> +    if (newTitle === '') {
```suggestion
    if (!newTitle) {
```

2023-06-17 06:36 UTC, sTorba24 approved these changes
Approved!

2023-07-06 01:01 UTC, closed without merging