first version
mate-academy/react_todo-app pull request #595
Opened 2023-07-20 19:04 UTC by sheva10barca

[DEMO LINK](https://sheva10barca.github.io/react_todo-app/)

2023-07-21 11:57 UTC, IvanFesenko requested changes
Your app work incorrect:
There are no animation on adding/deleting
Clear completede removes only one item
https://github.com/mate-academy/react_todo-app/assets/61904995/fb6ac8ae-63d4-4e98-83fd-364f45b83b63

2023-07-21 11:57 UTC, IvanFesenko commented on src/App.tsx
> +      : todo)));
its better to use prevSate
Fix all similar cases
```suggestion
    setTodos(prevTodos => prevTodos.map(...));
```

2023-07-21 11:57 UTC, IvanFesenko commented on src/App.tsx
> +  };
This handler should make all todos completed
Aslo dont forget about prevState

https://github.com/mate-academy/react_todo-app/assets/61904995/31f1927d-bb2d-470c-ad22-dc37543cbe9f

2023-07-21 11:57 UTC, IvanFesenko commented on src/types/Todo.ts
> +  // isLoading?: boolean;
Remove comments

2023-07-21 17:53 UTC, etojeDenys requested changes

2023-07-21 17:53 UTC, etojeDenys commented on src/components/Footer/Footer.tsx
> +  completedTodo: Todo[];
we don't need an array of todos, let's pass only nr

2023-07-21 17:53 UTC, etojeDenys commented on src/App.tsx
> +  const [todoTitle, setTodoTitle] = useState('');
we can move this state to Header and pass our title in handleSubmit

2023-07-22 09:35 UTC, etojeDenys requested changes

2023-07-22 09:35 UTC, etojeDenys commented on src/components/Header/Header.tsx
> +      <form onSubmit={(e) => handleSubmit(e, todoTitle, setTodoTitle)}>
we can only send todoTitle in handleSubmit, let's create some handler, and use `e.preventDefault` there and the same with resetting todoTitle

2023-07-22 10:52 UTC, etojeDenys approved these changes
lgtm

2025-02-09 20:02 UTC, closed without merging