init
mate-academy/react_todo-app pull request #668
Opened 2023-09-04 15:16 UTC by MaksymKos

https://maksymkos.github.io/react_todo-app/

2023-09-04 16:16 UTC, etojeDenys requested changes
1 item left
<img width="177" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/24b7e3fd-72ac-4406-aecb-46deedda6f58">

2023-09-04 16:16 UTC, etojeDenys commented on src/App.tsx
> +  } = todosContext;
```suggestion
  const {
    todos,
    addTodo,
    deleteCompletedTodos,
    handleToggleAll,
    incompletedTodosCount,
    hasCompletedTodos,
    filterTodos,
  } = useContext(TodosContext);
```

2023-09-04 16:16 UTC, etojeDenys commented on src/context/TodoContext.tsx
> +export const TodosContext = React.createContext<TodoContextType>({
let's create the custom hook to avoid redundant import 
```
export const useTodos = (): TodoContextType => React.useContext(TodosContext)
```

2023-09-07 16:55 UTC, TarasHoliuk requested changes
Well done :+1: 
I observed that the edit todo input does not become in focus properly - let's fix it

2023-09-07 16:55 UTC, TarasHoliuk commented on src/hooks/useLocalStorage.ts
> +  // useEffect(() => {
it's better to delete such comments

2023-09-07 16:55 UTC, TarasHoliuk commented on src/App.tsx
> +  };
these functions are redundant
you may use `setFilterStatus` everywhere you use `handleFilterChange` and so on

2023-09-07 16:55 UTC, TarasHoliuk commented on src/components/TodoItem.tsx
> +    if (!isEditing && inputRef.current) {
```suggestion
    if (isEditing && inputRef.current) {
```

2023-09-07 17:14 UTC, plodnikate approved these changes
good job !

2024-10-14 06:33 UTC, closed without merging