todo app
mate-academy/react_todo-app pull request #728
Opened 2023-10-13 13:19 UTC by donizer

[DEMO LINK](https://donizer.github.io/react_todo-app/)

2023-10-13 13:26 UTC, donizer commented
again as in this [case](https://github.com/mate-academy/react_dynamic-list-of-goods/pull/1850) i have the same issue.

During `npm i` it fails to find config file 
`ESLint couldn't find the config "@mate-academy/eslint-config-react-typescript" to extend from. Please check that the name of the config is correct.`

2023-10-13 15:04 UTC, loralevitska requested changes
Great job overall! Just couple tiny things needs to be fixed before approval)

- add right condition `1 item left`
![image](https://github.com/mate-academy/react_todo-app/assets/70009205/f0c60983-2d74-439b-8e16-7f6c38c17603)
- remove outline, it breaks design
- according your question, such files should be correct by default in your project. From which part of project did you run your command (maybe it was not from root file). If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-10-13 15:04 UTC, loralevitska commented on src/Contexts/Context.tsx
> +    // { id: +new Date(), completed: false, title: 'fiska' },
Remove comment. Try it write obvious code that explain all we need without comments) Fix all cases

2023-10-13 15:04 UTC, loralevitska commented on src/hooks/useLocalStorage.tsx
> +    if (data === null) {
```suggestion
    if (!data) {
```

2023-10-13 15:33 UTC, donizer commented
All styles was here initially. And outline present in [reference](https://todomvc.com/examples/vanillajs/)

2023-10-14 18:55 UTC, donizer commented
![image](https://github.com/mate-academy/react_todo-app/assets/52879984/a7b7f12e-bcdb-4d36-8524-549597fc3e81)

2023-10-15 08:52 UTC, Andriy-Shymkiv requested changes
- this arrow should be black when all todos is completed:
![image](https://github.com/mate-academy/react_todo-app/assets/102289654/788febfa-4c68-487b-a86d-191885bf3158)
 
the codebase looks good. left some comments

2023-10-15 08:52 UTC, Andriy-Shymkiv commented on src/App.tsx
> +        id: +new Date(),
you put date in id field? but why?

2023-10-15 08:52 UTC, Andriy-Shymkiv commented on src/App.tsx
> +  ) as DefaultValueType;
please give a better naming for this type

2023-10-15 08:52 UTC, Andriy-Shymkiv commented on src/Contexts/Context.tsx
> +  // }, [todos]);
please remove logs

2023-10-15 09:41 UTC, donizer commented on src/App.tsx
> +        id: +new Date(),
to use as a unique key 
```
Implement TodoApp component with an input field to create new todos on submit (Enter). Each item should have:

    id - unique identifier (+new Date() is good enough)
    title - the text of a todo
    completed - current status (false by default)
```

2023-10-15 11:16 UTC, SanyaBratashchuk approved these changes

2024-03-17 09:22 UTC, closed without merging