todo-app implementation
mate-academy/react_todo-app pull request #746
Opened 2023-10-26 08:58 UTC by yulabakun

[DEMO](https://yulabakun.github.io/react_todo-app/)

2023-10-26 16:23 UTC, OlegPopovych approved these changes
Good job! Just two comments.

2023-10-26 16:23 UTC, OlegPopovych commented on src/components/TodoHeader/TodoHeader.tsx
> +        <input
Add `onBlur` to `input` and call `handleFormSubmit` function.

2023-10-26 16:23 UTC, OlegPopovych commented on src/components/TodosContext/TodosContext.tsx
> +    //   .map(todo => (todo.id === updatedTodo.id ? updatedTodo : todo)));
Let's remove your  comments)

2023-10-27 08:00 UTC, StasSokolov requested changes
Almost done, let's improve your code a bit more, only few minor comments🔥

Check please demo link
<img width="1512" alt="Снимок экрана 2023-10-27 в 10 59 53" src="https://github.com/mate-academy/react_todo-app/assets/75898310/153848ca-d55e-4e75-9d4e-daa4ce8c0f96">

2023-10-27 08:20 UTC, yulabakun commented on src/components/TodosFilter/TodosFilter.tsx
> +            className={currentAppliedFilter === Status.All ? 'selected' : ''}
added cn library here because with logical operator typescript detected types incompatibility

2023-10-27 08:40 UTC, StasSokolov approved these changes
Awesome job🔥

2025-02-13 12:47 UTC, closed without merging