satge-1
mate-academy/react_todo-app pull request #782
Opened 2023-11-18 15:34 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_todo-app/)

2023-11-18 16:11 UTC, etojeDenys requested changes
1. show the clear completed button when we have at least one completed todo
2. should be 1 item left
<img width="849" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/3e242c0b-10c1-4dd2-b220-8b099850a013">
3. you should add the todo title as value in input 
<img width="683" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/97b2e479-7939-4a46-9c59-d6099ecf283d">

2023-11-18 16:11 UTC, etojeDenys commented on src/components/TodosFilter/TodosFilter.tsx
> +          className={crntFilterState === 'completed' ? 'selected' : ''}
we usually use classnames package for the conditional classes

2023-11-18 16:11 UTC, etojeDenys commented on src/components/TodoItem/TodoItem.tsx
> +                onChange={(event) => handleTodoChecked(event)}
```suggestion
                onChange={handleTodoChecked}
```
we can simplify it

2023-11-18 16:11 UTC, etojeDenys commented on src/components/TodoApp/TodoApp.tsx
> +            3 items left
you should show the real number

2023-11-19 07:59 UTC, Andriy-Shymkiv requested changes

2023-11-19 07:59 UTC, Andriy-Shymkiv commented on src/TodosContext.tsx
> +  }), [todos]);
do not ignore eslint warnings. `missing dependencies` is a very important rule

2023-11-19 07:59 UTC, Andriy-Shymkiv commented on src/components/TodoApp/TodoApp.tsx
> +  };
you can move it all to context

2023-11-19 07:59 UTC, Andriy-Shymkiv commented on src/components/TodoList/TodoList.tsx
> +    <ul className="todo-list" data-cy="todosList">
you can't pass the tests because of this `ul`. already answered about it in chat

2023-11-19 07:59 UTC, Andriy-Shymkiv commented on src/hooks/useLocalStorage.tsx
> +export function useLocalStorage<Ty>(
```suggestion
export function useLocalStorage<T>(
```

2023-11-19 07:59 UTC, Andriy-Shymkiv commented on src/types/Todo.ts
> +export type TodoId = Todo['id'];
do you really need a separate type for it?

2023-11-19 14:44 UTC, nazarmatsevych approved these changes

2025-04-22 17:02 UTC, closed without merging