first commit
mate-academy/react_todo-app pull request #799
Opened 2023-12-07 21:21 UTC by SerhiiUnhurian

[DEMO LINK](https://SerhiiUnhurian.github.io/react_todo-app/)

2023-12-08 10:42 UTC, etojeDenys requested changes
your demo link doesn't work, try to fix that firstly

2023-12-08 21:02 UTC, SerhiiUnhurian commented
i need help with this task

2023-12-09 07:34 UTC, loralevitska requested changes
Hi, if you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-12-10 12:44 UTC, etojeDenys requested changes
1. I can add the todo with an empty title
<img width="690" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/6171a0c2-7965-4f12-b7f5-94554b00ba24">

2. when I try to save the empty edited input, the todo must delete

3. The completed mark doesn't appear on the first todo
<img width="676" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/a1e4d937-7c64-4155-b390-68b452bdcd63">

2023-12-10 12:44 UTC, etojeDenys commented on src/App.tsx
> +      {/* <header className="header">
remove all comments

2023-12-11 16:46 UTC, Esceype requested changes
Need to fix:
- checkbox in a row for each todo should toggle completed status but it doesn`t work, it just set check mark in UI and that's all;
- toggle all should set all checkboxes to true and in UI user should see green check mark near each todo;
- if I will add string like this "          e             " that it will save it with spaces, but user can see it only when this todo will be in edit mode;
- add the alert-placeholder on edit mode in case when string is empty set there placeholder that will describe that if user will save it empty it will be deleted.

2023-12-12 11:59 UTC, denys-danyliuk requested changes
you should delete todos if their title is empty
<img width="620" alt="Знімок екрана 2023-12-12 о 13 58 55" src="https://github.com/mate-academy/react_todo-app/assets/106310796/5bb3701d-9099-43f1-8edc-fc1b088c0697">

2023-12-12 15:56 UTC, sTorba24 approved these changes
Well done! Little suggestions left

2024-09-18 20:32 UTC, closed without merging