add todo app
mate-academy/react_todo-app pull request #820
Opened 2023-12-28 16:43 UTC by Vlad4567

- [DEMO LINK](https://Vlad4567.github.io/react_todo-app/)

2023-12-28 19:39 UTC, anastasiia-tilikina requested changes
GJ!

let's make some fixes

1.  Clear completed button should be visible only when there are completed todos.
2. When I edit todo it should be deleted if new title is empty
3. Pls show some error message when I try to add todo with empty title (e.g. 'title shouldn't be empty')
4. there is some bug with left items count
![image](https://github.com/mate-academy/react_todo-app/assets/108538921/80105760-33d4-4a75-927c-9d3f6bef3680)
5. Move header and footer to separate components

2023-12-28 19:39 UTC, anastasiia-tilikina commented on src/App.tsx
> +        <form onSubmit={handleFormSubmit} onBlur={handleFormSubmit}>
I don't think that there is proper behaviour adding new todo onBlur

2023-12-28 19:39 UTC, anastasiia-tilikina commented on src/TodosContext.tsx
> +  }, [state]);
pls fix this linter error
![image](https://github.com/mate-academy/react_todo-app/assets/108538921/71fdca9c-85de-4ee8-af8e-b631ab2bcbe8)

2023-12-28 19:39 UTC, anastasiia-tilikina commented on src/components/TodoItem/TodoItem.tsx
> +  };
I believe this helper is redundant

2023-12-28 19:39 UTC, anastasiia-tilikina commented on src/components/TodoList/TodoList.tsx
> +  });
don't quite understand what are you doing here)
Why don't you map todos directly in your jsx?

2023-12-29 10:42 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2026-08-06 08:05 UTC, closed without merging