Fs on oct19 igor
mate-academy/react_todo-app pull request #87
Opened 2019-12-12 19:49 UTC by Igorskiy

[DEMO LINK](https://igorskiy.github.io/react_todo-app/)

2019-12-13 11:14 UTC, vpolets requested changes
юзер завичай не хоче для вибору чек боксу клацати тільки по ньому, весь todo має бути клікабельним, якщо я клацнув по todo - він змінив свій статус на !todo.completed

Пройдись ще раз по назвах і на майбутнє перечитуй код перед відправкою і подумай 2 рази чи відповідають назви методів і змінних тому що вони зберігають чи роблять

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  selectAllHandler = () => {
selectAllTodos

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  InputChangeHandler = (event) => {
назви методів з малої букви пишуться

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  InputChangeHandler = (event) => {
це Header метод, перенеси його туди

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  addTodoHandler = (event) => {
a чому addTodo обробляє івенти? З назви метода вона має приймати todo і додавати його в масив todo
```suggestion
  addTodo = (todo) => this.setState(prev => ({
    todos: [...prev.todos, todo],
    selectedFilter: FILTER_TYPES.all,
  }))
```
Ось так вона має виглядати і нічого більше:)

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +            id: +Date.now(),
Date.now() це число і так
```suggestion
            id: Date.now(),
```

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +      this.setState(state => ({
```suggestion
      this.setState(prevState => ({
```
називай речі своїми іменами

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  toggleHandler = (todoId) => {
```suggestion
  toggleTodoCompleted = (id) => {
```

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  removeHandler = (todoId) => {
deleteTodo

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  getFilterTodo = (currentFilter) => {
отримати фільтр туду(один)? що це значить?
getFilteredTodos
отримати (які?) відфільтровані (один чи масив?) тудушки (багато)

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +      case 'all': return todos;
використовуй константи для строки

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +      case 'completed': return todos.filter(todo => todo.completed);
```suggestion
      case FILTER_TYPES.completed: return todos.filter(todo => todo.completed);
```

2019-12-13 11:14 UTC, vpolets commented on src/App.js
> +  filterHandler = (filter, i) => {
setCurrentFilter

2019-12-13 16:16 UTC, Igorskiy commented on src/App.js
> +  addTodoHandler = (event) => {
Тоесть на обработчик onSubmit мне придется ставить 2 отдельные функции : одну, которая создает todo на основании введенного в инпуте формы title и другую, которая добавляет эту todo в массив. Зачем тогда в этом случае делать 2 функции, если функция создания todo с параметром title неразрывно связана с его добавлением в массив и дальнейши отображением?

2019-12-16 08:35 UTC, Igorskiy commented
> юзер завичай не хоче для вибору чек боксу клацати тільки по ньому, весь todo має бути клікабельним, якщо я клацнув по todo - він змінив свій статус на !todo.completed
> 
> Пройдись ще раз по назвах і на майбутнє перечитуй код перед відправкою і подумай 2 рази чи відповідають назви методів і змінних тому що вони зберігають чи роблять

2019-12-16 12:56 UTC, vkryvytskyy commented
Когда я нахожусь на вкладке completed, и добавляю новый todo, меня не должно перекидывать на вкладку all. todo должен появится только во вкладке all/active, а я должен остаться на той вкладке, на которой был

2019-12-16 13:50 UTC, vkryvytskyi approved these changes

2019-12-16 16:23 UTC, Igorskiy commented
В компоненте TodoItems я использовал autofocus для того, чтобы функционал совпадал с указанным в примере.

2019-12-16 17:24 UTC, vkryvytskyy commented
![image](https://user-images.githubusercontent.com/38065883/70928344-86804780-2039-11ea-85aa-08bb630dfef0.png
Сделай так, чтобы если я стираю все из туду в режиме редактирования - он удалялся, а не оставался пустым

2019-12-17 09:14 UTC, vkryvytskyy commented
![image](https://user-images.githubusercontent.com/38065883/70981664-3f886580-20be-11ea-8c60-a5f74ad16bbb.png)
Добавь проверку if 
```
(inputValue.trim() === '') { return }
```

2026-03-03 10:06 UTC, closed without merging