solution
mate-academy/react_todo-app pull request #914
Opened 2024-03-16 19:04 UTC by BodyaKutsyk

[DEMO LINK](https://BodyaKutsyk.github.io/react_todo-app/)

2024-03-17 07:56 UTC, Andriy-Shymkiv requested changes
1. the user should be able to complete a specific todo, but not all at once
2. toggle todos button is not working
3. todo editing is not working

2024-03-17 07:56 UTC, Andriy-Shymkiv commented on src/components/TodoApp/TodoApp.tsx
> +      {filterTodos(todos, Status.all).length > 0 && (
this can be memoized

2024-03-17 07:56 UTC, Andriy-Shymkiv commented on src/components/TodoApp/TodoApp.tsx
> +            {`${filterTodos(todos, Status.active).length} items left`}
ass well here

2024-03-17 07:56 UTC, Andriy-Shymkiv commented on src/components/TodoApp/TodoApp.tsx
> +          {filterTodos(todos, Status.completed).length > 0 && (
here the same

2024-03-17 07:56 UTC, Andriy-Shymkiv commented on src/components/TodoList/TodoList.tsx
> +  const filteredTodos = filterTodos(todos, filter);
memoize

2024-03-17 07:56 UTC, Andriy-Shymkiv commented on src/components/TodoItem/TodoItem.tsx
> +      inputActive.current.value = currentTodo.title;
it doesn't make sense to store a title in ref, use it only for focus

2024-03-17 16:33 UTC, volodymyr-soltys97 requested changes
Good job 👍 
To improve:
The title cannot be an empty
<img width="773" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/64750958/42e6fcfc-eaa8-4f59-982a-39c6d3594407">

2024-03-17 18:17 UTC, volodymyr-soltys97 requested changes
Still not fixed from the previous review
<img width="711" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/64750958/ede1ff5d-2e6d-4758-bc53-a6db4d517033">

When I choose completed, the entire footer hides and I can't switch to another, this needs to be fixed
<img width="686" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/64750958/43968a0b-705b-483e-8749-7d407ec112bc">

2024-03-18 16:52 UTC, sTorba24 approved these changes

2024-03-18 16:52 UTC, sTorba24 commented on src/components/TodoApp/TodoApp.tsx
> +    if (!title || title.trim().length === 0) {
```suggestion
    if (!title || !title.trim()) {
```

2024-03-18 16:52 UTC, sTorba24 commented on src/components/TodoItem/TodoItem.tsx
> +        if (editedTitle.length === 0) {
```suggestion
        if (!editedTitle) {
```

2026-07-11 19:06 UTC, closed without merging