solution
mate-academy/react_todo-app pull request #962
Opened 2024-04-21 08:52 UTC by andreyysak

[DEMO LINK](https://andreyysak.github.io/react_todo-app/)

2024-04-21 09:31 UTC, SanyaBratashchuk requested changes

2024-04-21 09:31 UTC, SanyaBratashchuk commented on src/App.tsx
> +    ]);
```suggestion
    setTodos(prevTodos => [
      ...prevTodos,
      {
        id: Date.now(),
        title: query.trim(),
        completed: false,
      },
    ]);
```

2024-04-21 09:31 UTC, SanyaBratashchuk commented on src/App.tsx
> +      ),
```suggestion
    setTodos(prevTodos =>
      prevTodos.map(todo =>
        todo.id === id
          ? { ...todo, title: newTitle.trim(), isEditing: false }
          : todo,
      ),
```

2024-04-21 09:31 UTC, SanyaBratashchuk commented on src/App.tsx
> +    }
use switch case here. Also create an enum for todo statuses

2024-04-21 09:31 UTC, SanyaBratashchuk commented on src/components/Footer.tsx
> +        {activeTodosCount} items left
handle plural form it should be `1 item left` but `2 items left`

2024-04-24 12:52 UTC, anastasiiavorobiova requested changes
Great work! Consider fixing the layout. 
<img width="835" alt="Screenshot 2024-04-24 at 15 48 35" src="https://github.com/mate-academy/react_todo-app/assets/135232001/b4e3ca93-11e5-490c-9cc3-df8e01723a99">
<img width="896" alt="Screenshot 2024-04-24 at 15 49 29" src="https://github.com/mate-academy/react_todo-app/assets/135232001/ada84633-d287-46dd-9b65-b477802c4bf3">
<img width="844" alt="Screenshot 2024-04-24 at 15 50 28" src="https://github.com/mate-academy/react_todo-app/assets/135232001/6d81a327-ba3f-4f37-b7ea-626d89cc2aa2">
The title of the edited todo in the input changes to the previous on the next edit

2024-05-01 07:30 UTC, etojeDenys requested changes
1. looks too big
<img width="786" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/58ddd437-fa9b-4ad3-8eb8-2989782a5f30">

2. i can add empty todos, let's fix that
<img width="650" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/1e4cc189-1ecf-4900-83af-646ac1bc9362">

3. Did you choose not to use context here?
<img width="398" alt="image" src="https://github.com/mate-academy/react_todo-app/assets/70220667/5b493962-47d8-4da3-b021-f51b0da2711b">

2024-05-15 18:50 UTC, closed without merging